### PR TITLE
Bugfix/features-not-deleted

### PR DESCRIPTION
**Pull request by hackermd**
This PR addresses issue TissueMAPS/TissueMAPS#93

### CODE REVIEW

**Comment by hackermd** [comment]
I just noticed that an older changed (commit 9e1e052) got included into this PR. This should also be included into the develop branch, but is independent of issue #93

**Comment by riccardomurri** [comment]
LGTM, I would merge

**Comment by hackermd** [comment]
> there's already quite some TM instances deployed, whose data on the DB will be left untouched by this commit -- those instances will not be exporting correct data unless one re-runs the pipeline(s), which is annoying at least...

As long as the pipeline has not be re-run this should not pose a problem.

**Comment by hackermd** [comment]
Thanks @riccardomurri 

> if an exception happens between the two session...delete() at lines 237--239 and 240--242, then the second one will not be executed ever again;

Ideally this would be handled by the database in form of a foreign key constraint. Unfortunately, it has not been possible to define a reference from a distributed table to a non-distributed table for this use case (see citusdata/citus_docs#209). Maybe this is now possible; please refer to [citus docs on reference tables](https://docs.citusdata.com/en/v7.1/dist_tables/ddl.html#reference-tables).

**Pull request merged**
