### PR TITLE
Make workflow description keys optional

### PR DESCRIPTION
**Pull request by hackermd**
- stage ``mode`` is set to ``sequential`` by default
- step ``active`` defaults to ``True``

### CODE REVIEW

**Comment by sparkvilla** [comment]
@hackermd Two things: Is this a new feature or a fix? in the first case it needs to be branched off and merged to develop. How this can be best tested?

**Comment by hackermd** [comment]
This is a fix! It can be tested by uploading a workflow description in YAML format, which lacks the ``mode`` and ``active`` keys. The correct default values should then be used server side.

**Comment by sparkvilla** [comment]
@hackermd Have you already tested it? if not, it would be great to have a test case to try this out..do you have something?

**Comment by riccardomurri** [comment]
Merged, thanks!

**Pull request merged**
