### PR TITLE
Search for JtModules in multiple directories 

### PR DESCRIPTION
**Pull request by riccardomurri**
This patch allows setting multiple directories to be searched for Jterator modules.
it also changes the location of the "handles" file: it should now be *aside* the module file it refers to. For example, module `/home/tissuemaps/jtmodules/foo.py` will have the handles file in `/home/tissuemaps/jtmodules/foo.handles.yaml`.

Apart from that, the logic for determining what is a valid module file is not changed.

The new default module search path is done for the new JtModules/JtLibrary repo layout (see https://github.com/TissueMAPS/JtLibrary/pull/15) but also retain compatibility with TM v0.3.3

### CODE REVIEW

**Comment by riccardomurri** [comment]
Code is as yet *untested*.

**Comment by riccardomurri** [comment]
@jluethi This is what should be needed to test the "identify primary iterative" MATLAB code.

**Comment by riccardomurri** [comment]
@jluethi @sparkvilla I have tested this PR and TissueMAPS/JtLibrary#15 with the "v0.3.3/CellVoyager_2D_Canonical" test data set and they work.

**Comment by sparkvilla** [comment]
@riccardomurri This pull request should be paired with TissueMAPS/JtLibrary#15, right? Because I tried to test this one alone (using "v0.3.4/CellVoyager_2D_SpotDetection_Scott") and the available modules are not showing up

**Comment by riccardomurri** [comment]
> This pull request should be paired with TissueMAPS/JtLibrary#15, right?

Yes.

**Comment by sparkvilla** [comment]
This works for all tests together with TissueMAPS/JtLibrary#15

**Pull request merged**
